package com.bid.data;

// Generated 2010-1-11 22:43:10 by Hibernate Tools 3.2.4.GA

/**
 * Sorts generated by hbm2java
 */
public class Sorts implements java.io.Serializable {

	private long sortId;
	private String sortName;

	public Sorts() {
	}

	public Sorts(long sortId) {
		this.sortId = sortId;
	}

	public Sorts(long sortId, String sortName) {
		this.sortId = sortId;
		this.sortName = sortName;
	}

	public long getSortId() {
		return this.sortId;
	}

	public void setSortId(long sortId) {
		this.sortId = sortId;
	}

	public String getSortName() {
		return this.sortName;
	}

	public void setSortName(String sortName) {
		this.sortName = sortName;
	}

}
