package com.bid.data;

// Generated 2010-1-12 21:13:35 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Sorts generated by hbm2java
 */
public class Sorts implements java.io.Serializable {

	private long sortId;
	private String sortName;
	private Set<Items> itemses = new HashSet<Items>(0);

	public Sorts() {
	}

	public Sorts(String sortName) {
		this.sortName = sortName;
	}

	public Sorts(String sortName, Set<Items> itemses) {
		this.sortName = sortName;
		this.itemses = itemses;
	}

	public long getSortId() {
		return this.sortId;
	}

	public void setSortId(long sortId) {
		this.sortId = sortId;
	}

	public String getSortName() {
		return this.sortName;
	}

	public void setSortName(String sortName) {
		this.sortName = sortName;
	}

	public Set<Items> getItemses() {
		return this.itemses;
	}

	public void setItemses(Set<Items> itemses) {
		this.itemses = itemses;
	}

}
