package com.bid.data;

// Generated 2010-1-11 0:22:20 by Hibernate Tools 3.2.4.GA

/**
 * Sorts generated by hbm2java
 */
public class Sorts implements java.io.Serializable {

	private int sortId;
	private String sortName;

	public Sorts() {
	}

	public Sorts(int sortId) {
		this.sortId = sortId;
	}

	public Sorts(int sortId, String sortName) {
		this.sortId = sortId;
		this.sortName = sortName;
	}

	public int getSortId() {
		return this.sortId;
	}

	public void setSortId(int sortId) {
		this.sortId = sortId;
	}

	public String getSortName() {
		return this.sortName;
	}

	public void setSortName(String sortName) {
		this.sortName = sortName;
	}

}
