package com.bid.data;

// Generated 2010-1-12 21:13:35 by Hibernate Tools 3.2.4.GA

/**
 * Deposits generated by hbm2java
 */
public class Deposits implements java.io.Serializable {

	private DepositsId id;
	private Users users;
	private Items items;
	private Double moneyFrozen;

	public Deposits() {
	}

	public Deposits(DepositsId id, Users users, Items items) {
		this.id = id;
		this.users = users;
		this.items = items;
	}

	public Deposits(DepositsId id, Users users, Items items, Double moneyFrozen) {
		this.id = id;
		this.users = users;
		this.items = items;
		this.moneyFrozen = moneyFrozen;
	}

	public DepositsId getId() {
		return this.id;
	}

	public void setId(DepositsId id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

	public Double getMoneyFrozen() {
		return this.moneyFrozen;
	}

	public void setMoneyFrozen(Double moneyFrozen) {
		this.moneyFrozen = moneyFrozen;
	}

}
